---
driver:
  name: vagrant
  network:
    - ["private_network", { type: "dhcp" }]

provisioner:
  name: nodes
  roles_path: test/fixtures/roles

platforms:
- name: ubuntu-12.04
  run_list:
  - recipe[apt]
  driver_config:
    box: hashicorp/precise64

- name: windows-2016
  driver_config:
    gui: true
    box: mwrock/Windows2016

- name: windows-2008R2
  driver_config:
    gui: true
    box: opentable/win-2008r2-datacenter-amd64-nocm

suites:
- name: node1
  run_list:
  - role[test_json_role]
  - role[test_ruby_role]
  - recipe[node-tests::node1]
  attributes:
    consul:
      config:
        bootstrap_expect: 2
        server: true
        
- name: node2
  run_list:
  - recipe[hurry-up-and-test::set_non_nat_vbox_ip]
  - recipe[node-tests::node2]
  attributes:
    consul:
      config:
        bootstrap_expect: 2
        server: true
